### ISSUE TITLE
Proteger acesso a branch master

### ISSUE THREAD

**Issue by GersonDantas** [sidnei-junior/rodizio-da-galera#9]
- [x] @sidnei-junior Dar acesso ADM a Gerson
- [x] Validar se é possível bloquear a main para ser apenas via git merge
- [x] Gerson fazer configuração baseado no padrão Git Flow
     - https://www.alura.com.br/artigos/git-flow-o-que-e-como-quando-utilizar

**Comment by sidnei-junior** [comment]
It's not possible to add permission on public repo
